# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    labels:
      - "dependencies"
      - "javascript"
    schedule:
      interval: "daily"
      time: "05:30"
      timezone: "Europe/Berlin"
    allow:
      - dependency-type: "all"
    groups:
      non-major-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      non-major-security-updates:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"
